### PR TITLE
Add get_version, get_serialnum, and viewport

### PR DESCRIPTION
**Pull request by ehendrix23**
Add calls for get_version and get_serialnum.
Add ability for viewPort allowing to retrieve information for the PIP window.

Not fully tested yet but already wanted you to have a look at.

Note, I also updated based on flake8/pylint.

### CODE REVIEW

**Comment by sentry07** [comment]
I no longer have access to a DirecTV receiver so I can't test this. @firstof9 can you check?

**Comment by firstof9** [comment]
Sure gimmie a couple days.

**Comment by firstof9** [comment]
Both "primary" and "secondary" give me the same data with two different channels on screen:

```
{
    "callsign": "CNeHD",
    "date": "20160623",
    "duration": 900,
    "episodeTitle": "Think About Your Future",
    "isOffAir": false,
    "isPclocked": 3,
    "isPpv": false,
    "isRecording": false,
    "isVod": false,
    "major": 296,
    "minor": 65535,
    "offset": 844,
    "programId": "66583828",
    "rating": "TV-PG",
    "startTime": 1542554100,
    "stationId": 3900953,
    "status": {
        "code": 200,
        "commandResult": 0,
        "msg": "OK.",
        "query": "/tv/getTuned?clientAddr=0&videoWindow=secondary"
    },
    "title": "Teen Titans Go!"
}
```
```
{
    "callsign": "CNeHD",
    "date": "20160530",
    "duration": 900,
    "episodeTitle": "Operation Dude Rescue: Part 1",
    "isOffAir": false,
    "isPclocked": 3,
    "isPpv": false,
    "isRecording": false,
    "isVod": false,
    "major": 296,
    "minor": 65535,
    "offset": 78,
    "programId": "36256552",
    "rating": "TV-PG",
    "startTime": 1542555000,
    "stationId": 3900953,
    "status": {
        "code": 200,
        "commandResult": 0,
        "msg": "OK.",
        "query": "/tv/getTuned?clientAddr=0&videoWindow=primary"
    },
    "title": "Teen Titans Go!"
}
```

get_version and get_serialnum functions work fine.

**Comment by firstof9** [comment]
@sentry07 look ready to merge

**Comment by sentry07** [comment]
Thanks.

**Comment by ehendrix23** [comment]
@sentry07 , looks like pypi did not get updated. Figuring for that to happen setup.py needs to be updated as well.
I just created a new pull request updating this file (changing the version in there to 0.6).

**Comment by sentry07** [comment]
I'll get PyPi updated to 0.6 tonight.

**Comment by ehendrix23** [comment]
@sentry07, little ping for getting PyPi updated. :-)

**Comment by sentry07** [comment]
Nag nag nag. Just like my wife. If I say I'll get it done, you don't have to keep reminding me every 6 months!

**Comment by ehendrix23** [comment]
Thank you!!!

I can get the component version updated no worries. Going to be using some of the new methods within the DirecTV platform in HASS anyways and part of that will then do the increase.

**Comment by sentry07** [comment]
Great! Nevermind Bahnburner.

**Comment by Bahnburner** [comment]
Ok. I'm here if you need me.

**Pull request merged**
