### PR TITLE
Error checking if clientAddr missing/bad

### PR DESCRIPTION
**Pull request by firstof9**
* Add error checking if the clientAddr is bad or missing resulting in an
error code being returned

### CODE REVIEW

**Comment by sentry07** [comment]
Thanks for the update. I don't have Directv anymore, so I don't have any way to test but it looks ok. :)

**Comment by firstof9** [comment]
If the clientAddr is queried and doesn't exist or isn't found you get a status code of 403, checking for a 200 code just seems easier. Glad to help!

**Comment by firstof9** [comment]
Mind updating/uploading to PyPi? Would be appreciated.

**Comment by sentry07** [comment]
I'm trying to figure out how. Someone uploaded the package before but I'm not sure how to update it.

**Comment by sentry07** [comment]
Ok, so one of the other contributors uploaded it to pypi so he has ownership of the index at the moment. I'm trying to get him to give me access. Will be directpy-0.2 when it's updated.

**Comment by firstof9** [comment]
Thank you

**Comment by sentry07** [comment]
Package has been updated on PyPi to version 0.2.

**Comment by firstof9** [comment]
Excellent thanks again @sentry07

**Pull request merged**
